name: quick-test

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENCE
      - CODEOWNERS

jobs:
  test-build:
    runs-on: ktbs-small-runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Tests
        run: make test
